// <auto-generated />
using System;
using AppBus.Web.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBus.Web.Migrations
{
    [DbContext(typeof(BusContext))]
    [Migration("20221108184853_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppBus.Web.Models.Avaliacao", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("OnibusId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DC_COMENTARIO");

                    b.Property<int>("Nota")
                        .HasColumnType("int")
                        .HasColumnName("DS_NOTA");

                    b.HasKey("UsuarioId", "OnibusId");

                    b.HasIndex("OnibusId");

                    b.ToTable("Tbl_AVALIACAO");
                });

            modelBuilder.Entity("AppBus.Web.Models.Bilhete", b =>
                {
                    b.Property<string>("BilheteId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NM_TITULAR");

                    b.Property<string>("NumeroBilhete")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("NR_BILHETE");

                    b.Property<int>("TipoBilhete")
                        .HasColumnType("int")
                        .HasColumnName("DS_TIPO_BILHETE");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_VALOR");

                    b.HasKey("BilheteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tbl_BILHETE");
                });

            modelBuilder.Entity("AppBus.Web.Models.CartaoCredito", b =>
                {
                    b.Property<string>("CartaoCreditoId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<int>("Bandeira")
                        .HasColumnType("int")
                        .HasColumnName("DS_Bandeira");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("NR_CVV");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("NR_CPF");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NM_TITULAR");

                    b.Property<string>("NumeroCartao")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("NR_Cartao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Validade")
                        .HasMaxLength(3)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_VALIDADE");

                    b.HasKey("CartaoCreditoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tbl_CARTAO_CREDITO");
                });

            modelBuilder.Entity("AppBus.Web.Models.Onibus", b =>
                {
                    b.Property<int>("OnibusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OnibusId"), 1L, 1);

                    b.Property<bool>("Acessivel")
                        .HasColumnType("bit")
                        .HasColumnName("FL_ACESSIVEL");

                    b.Property<string>("Linha")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("NR_LINHA");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NR_NUMERO");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NM_REGIAO");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("DC_STATUS");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_Valor");

                    b.Property<int>("TipoOnibusId")
                        .HasColumnType("int");

                    b.HasKey("OnibusId");

                    b.HasIndex("TipoOnibusId");

                    b.ToTable("Tbl_ONIBUS");
                });

            modelBuilder.Entity("AppBus.Web.Models.TipoOnibus", b =>
                {
                    b.Property<int>("TipoOnibusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoOnibusId"), 1L, 1);

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("DS_TIPO");

                    b.HasKey("TipoOnibusId");

                    b.ToTable("Tbl_TIPO_ONIBUS");
                });

            modelBuilder.Entity("AppBus.Web.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("NR_CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NM_NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DS_SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("DS_TELEFONE");

                    b.HasKey("UsuarioId");

                    b.ToTable("Tbl_USUARIO");
                });

            modelBuilder.Entity("AppBus.Web.Models.Avaliacao", b =>
                {
                    b.HasOne("AppBus.Web.Models.Onibus", "Onibus")
                        .WithMany("Avaliacao")
                        .HasForeignKey("OnibusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppBus.Web.Models.Usuario", "Usuario")
                        .WithMany("Avaliacao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onibus");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppBus.Web.Models.Bilhete", b =>
                {
                    b.HasOne("AppBus.Web.Models.Usuario", "Usuario")
                        .WithMany("Bilhetes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppBus.Web.Models.CartaoCredito", b =>
                {
                    b.HasOne("AppBus.Web.Models.Usuario", "Usuario")
                        .WithMany("Cartoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppBus.Web.Models.Onibus", b =>
                {
                    b.HasOne("AppBus.Web.Models.TipoOnibus", "TipoOnibus")
                        .WithMany()
                        .HasForeignKey("TipoOnibusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoOnibus");
                });

            modelBuilder.Entity("AppBus.Web.Models.Onibus", b =>
                {
                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("AppBus.Web.Models.Usuario", b =>
                {
                    b.Navigation("Avaliacao");

                    b.Navigation("Bilhetes");

                    b.Navigation("Cartoes");
                });
#pragma warning restore 612, 618
        }
    }
}
